name: "Performance Issue"
title: "[Performance Issue] "
labels: [performance]
assignees: []
description: "Report slow or inefficient type generation processes."
body:
  - type: markdown
    attributes:
      value: |
        ## Performance Issue
        Describe the performance problem in detail.
  - type: textarea
    id: issue_description
    attributes:
      label: "Issue Description"
      description: "Detailed description of the performance problem"
      placeholder: "Describe the issue..."
      required: true
  - type: dropdown
    id: affected_area
    attributes:
      label: "Affected Area"
      description: "Select the part of the repository affected"
      options:
        - "Type Generation"
        - "Build Scripts"
        - "CI/CD"
        - "Other"
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Include any profiling data, logs, or other information"
      placeholder: "Optional additional details..."
