name: "Specification Update"
title: "[Spec Update] "
labels: [spec update]
assignees: []
description: "Report updates to web standards affecting the DOM typings."
body:
  - type: markdown
    attributes:
      value: |
        ## Specification Update
        Provide details about the updated specification.
  - type: input
    id: spec_name
    attributes:
      label: "Specification Name"
      description: "Name of the updated specification"
      placeholder: "e.g., HTML Living Standard"
      required: true
  - type: input
    id: spec_link
    attributes:
      label: "Specification Link"
      description: "URL to the specification update"
      placeholder: "e.g., https://whatwg.org/"
      required: true
  - type: textarea
    id: impact_details
    attributes:
      label: "Impact Details"
      description: "Describe how the update affects the DOM typings"
      placeholder: "Details on the changes..."
      required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any other related information or references"
      placeholder: "Optional details..."
