name: "Web API type definition issue"
title: "[Web API type definition issue] "
labels: [lib.d.ts bug]
assignees: []
description: "Report inconsistencies between TypeScript's web API typings and browser behavior."
body:
  - type: markdown
    attributes:
      value: |
        ## Web API Type Definition Issue
        Provide details of the issue.
  - type: input
    id: issue_summary
    attributes:
      label: "Summary"
      description: "Brief summary of the issue"
      placeholder: "e.g., Mismatch in event handling..."
    validations:
      required: true
  - type: textarea
    id: expected_vs_actual
    attributes:
      label: "Expected vs. Actual Behavior"
      description: "Describe what you expected and what actually happened"
      placeholder: "Expected: ...\nActual: ..."
    validations:
      required: true
  - type: input
    id: playground_link
    attributes:
      label: "Playground Link"
      description: "Paste the TypeScript playground link"
      placeholder: "https://www.typescriptlang.org/play/..."
    validations:
      required: true
  - type: checkboxes
    id: browser_support
    attributes:
      label: "Browser Support"
      description: "Ensure that the API is supported in at least two major browser engines (not two Chromium-based browsers)."
      options:
        - label: "This API is supported in at least two major browser engines (not two Chromium-based browsers)."
          required: true
  - type: checkboxes
    id: use_latest_typescript
    attributes:
      label: "Have Latest TypeScript Package"
      description: "Ensure you are using the latest TypeScript version."
      options:
        - label: "I am using the latest version of TypeScript."
          required: true
  - type: checkboxes
    id: use_latest_typescript_web
    attributes:
      label: "Use the Latest @types/web Package"
      description: "Ensure you have tried the latest `@types/web` package."
      options:
        - label: "I am using the latest version of `@types/web`."
          required: true
  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Any extra information, logs, or references."
      placeholder: "Optional details..."
